[package]
name = "ace_insurance"
version = "0.1.0"
description = "Decentralized Hack Insurance on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ace_insurance"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "2.1.0"
